[tool.poetry]
name = "damysos"
version = "4.0.0-beta.34"
description = "ğŸ“ Programme Python qui permet de crÃ©er des documents personalisÃ©s."
authors = ["Laurent Bourgon <laurent.bourgon@outlook.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/BourgonLaurent/Damysos"
exclude = ["**/*.ui", "**/*.qrc"]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
docxtpl = "0.11.5"
PySide2 = "5.15.2"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
bandit = "^1.7.0"
ipywidgets = "^7.6.3"
notebook = "^6.4.0"

[tool.poetry.scripts]
damysos-build-resources = "build_resources:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
