[tool.poetry]
name = "damysos"
version = "4.0.0-beta.35"
description = "ğŸ“ Programme Python qui permet de crÃ©er des documents personalisÃ©s."
authors = ["Laurent Bourgon <laurent.bourgon@outlook.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/BourgonLaurent/Damysos"
exclude = [
    # files that are translated to .py
    "**/*.ui",
    "**/*.qrc",
    # included in .qrc files
    "damysos/ui/designer/fonts/",
    "damysos/ui/designer/icons/",
    "damysos/ui/designer/designer_styles.qss"
]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
docxtpl = "0.11.5"
PySide6 = "^6.1.2"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
bandit = "^1.7.0"
ipywidgets = "^7.6.3"
notebook = "^6.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
